name: CI

# Controls when the workflow will run test
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
